### ISSUE TITLE
RAW photo support

### ISSUE THREAD

**Issue by yeahitsjan** [bitgato/tasveer#1]
Awesome little tool! I really like it. Is there some kind of way to include RAW photos (.CR2, .NEF etc.)? This could highly increase my photography work. Probably QtRaw could help out here. I also experimented with it and it is very usable!

**Comment by bitgato** [comment]
Thanks! I'm glad you like it. I'm actually working on supporting more file types. Also, thank for suggesting QtRaw. I'll look into it!

**Comment by bitgato** [comment]
Hey! RAW file types (and a few others) are now supported. You can also use QTRaw if you want. Have a look at the README for details.

**Comment by yeahitsjan** [comment]
Awesome! Many thanks! I'll try out later :)
