### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by yeahitsjan** [bitgato/tasveer#2]
I don't know if its on the agenda (or would be too much for such a small tool) but how about adding a dark theme (switchable from a preferences dialog)?
I currently run a Linux Mint with XFCE in full dark but the app does not fit very much in it with its default light theme.

**Comment by bitgato** [comment]
Hey! If you look at the screenshots, I'm actually using a dark theme on my machine as well. I think what you really need is a global QT theme. On Mint, maybe do:
`sudo apt install qt5ct qt5-gtk-platformtheme qt5-gtk2-platformtheme`

Then in `Qt5 Settings` (`qt5ct`), you can change the themes. You can also set GTK theme to work with QT by selecting `gtk2`. I might have missed a few steps here but there's plenty of information on this online.

Also, this way, your other Qt softwares will look like your native GTK theme as well! Works like a charm on XFCE, which I'm using too.

**Comment by yeahitsjan** [comment]
Thanks for that, I will try that out later! Still would be awesome to have if you run it on Windows.. :)

**Comment by bitgato** [comment]
Hmm. Yeah. But I'll be honest, Windows is not really a priority right now. And yes adding themes would be against the "minimalistic" aspect of the program imo. But I'm open to pull requests if someone else implements it.
